# Numpy useful functions

In [72]:
import numpy as np
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [73]:
np.eye(2)
np.zeros((2,3))
np.ones((2,3))
c = np.random.randint(10, size=(1,6,3))

In [74]:
c.shape 
len(c)  # size of first dimension
c.ndim  # number of dimensions (2)
c.size  # number of elements (6)

18

In [75]:
np.arange(0,90,5) # like function range with step 5
np.linspace(0,90,10) # 10 elements from 0 to 90

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.])

In [76]:
d = c.ravel() # flatten the array
d = c.reshape((1,18))

In [77]:
np.append(a,d) # append arrays

array([1, 2, 3, 4, 5, 6, 4, 4, 3, 1, 3, 2, 9, 9, 9, 0, 3, 2, 9, 1, 5, 3, 3,
       4])

In [78]:
e = np.broadcast_to(d, (3,18)) # duplicate an array

In [79]:
np.flip(e,1)

array([[4, 3, 3, 5, 1, 9, 2, 3, 0, 9, 9, 9, 2, 3, 1, 3, 4, 4],
       [4, 3, 3, 5, 1, 9, 2, 3, 0, 9, 9, 9, 2, 3, 1, 3, 4, 4],
       [4, 3, 3, 5, 1, 9, 2, 3, 0, 9, 9, 9, 2, 3, 1, 3, 4, 4]])